// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagementSystem.Data;

#nullable disable

namespace OrderManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241017071115_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderManagementSystem.Models.Billing", b =>
                {
                    b.Property<string>("Billing_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Billing_Account_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("User_ID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Billing_ID");

                    b.HasIndex("Billing_Account_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Billings");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.BillingAccount", b =>
                {
                    b.Property<string>("Billing_Account_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Account_Balance")
                        .HasColumnType("float");

                    b.Property<string>("User_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Billing_Account_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("BillingAccounts");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.Cost", b =>
                {
                    b.Property<string>("Cost_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cost_ID");

                    b.ToTable("Costs");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.FreightOutbound", b =>
                {
                    b.Property<string>("Outbound_Order_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<DateTime>("Creation_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Estimated_Delivery_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FBA_Shipment_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FBA_Tracking_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Order_Ship_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Order_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outbound_Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Product_Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recipient_Post_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference_Order_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Related_Adjustment_Order")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shipping_Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tracking_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Transport_Days")
                        .HasColumnType("int");

                    b.Property<string>("Warehouse_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Outbound_Order_ID");

                    b.HasIndex("Warehouse_ID");

                    b.ToTable("FreightOutbounds");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.FreightProductList", b =>
                {
                    b.Property<string>("Order_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Product_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FreightOutboundOutbound_Order_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InventoryProduct_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Order_ID", "Product_ID");

                    b.HasIndex("FreightOutboundOutbound_Order_ID");

                    b.HasIndex("InventoryProduct_ID");

                    b.ToTable("FreightProductLists");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.InboundOrder", b =>
                {
                    b.Property<string>("Inbound_Order_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Arrival_Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Boxes")
                        .HasColumnType("int");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<DateTime>("Creation_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Estimated_Arrival")
                        .HasColumnType("datetime2");

                    b.Property<string>("Inbound_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Product_Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reference_Order_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tracking_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Warehouse_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Inbound_Order_ID");

                    b.HasIndex("Warehouse_ID");

                    b.ToTable("InboundOrders");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.InboundProductList", b =>
                {
                    b.Property<string>("Order_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Product_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Order_ID", "Product_ID");

                    b.HasIndex("Product_ID");

                    b.ToTable("InboundProductLists");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.Inventory", b =>
                {
                    b.Property<string>("Product_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Product_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Warehouse_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Product_ID");

                    b.HasIndex("Warehouse_ID");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.ParcelOutbound", b =>
                {
                    b.Property<string>("Order_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Boxes")
                        .HasColumnType("int");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Delivery_Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Estimated_Delivery_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Internet_Posting_Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Latest_Information")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference_Order_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Related_Adjustment_Order")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ship_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Shipping_Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tracking_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tracking_Update_Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Transport_Days")
                        .HasColumnType("int");

                    b.Property<string>("Warehouse_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Order_ID");

                    b.HasIndex("Warehouse_ID");

                    b.ToTable("ParcelOutbounds");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.ParcelProductList", b =>
                {
                    b.Property<string>("Order_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Product_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Order_ID", "Product_ID");

                    b.HasIndex("Product_ID");

                    b.ToTable("ParcelProductLists");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.PlatformOrder", b =>
                {
                    b.Property<string>("Order_ID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Order_ID");

                    b.ToTable("PlatformOrders");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.Role", b =>
                {
                    b.Property<string>("Role_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Role_ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.User", b =>
                {
                    b.Property<string>("User_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date_Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.UserRole", b =>
                {
                    b.Property<string>("User_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Role_ID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("User_ID", "Role_ID");

                    b.HasIndex("Role_ID");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.Warehouse", b =>
                {
                    b.Property<string>("Warehouse_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Warehouse_ID");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.Billing", b =>
                {
                    b.HasOne("OrderManagementSystem.Models.BillingAccount", "BillingAccount")
                        .WithMany("Billings")
                        .HasForeignKey("Billing_Account_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagementSystem.Models.User", null)
                        .WithMany("Billings")
                        .HasForeignKey("User_ID");

                    b.Navigation("BillingAccount");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.BillingAccount", b =>
                {
                    b.HasOne("OrderManagementSystem.Models.User", "User")
                        .WithMany("BillingAccounts")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.FreightOutbound", b =>
                {
                    b.HasOne("OrderManagementSystem.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("Warehouse_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.FreightProductList", b =>
                {
                    b.HasOne("OrderManagementSystem.Models.FreightOutbound", "FreightOutbound")
                        .WithMany()
                        .HasForeignKey("FreightOutboundOutbound_Order_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagementSystem.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("InventoryProduct_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FreightOutbound");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.InboundOrder", b =>
                {
                    b.HasOne("OrderManagementSystem.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("Warehouse_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.InboundProductList", b =>
                {
                    b.HasOne("OrderManagementSystem.Models.InboundOrder", "InboundOrder")
                        .WithMany("InboundProductLists")
                        .HasForeignKey("Order_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagementSystem.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("Product_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InboundOrder");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.Inventory", b =>
                {
                    b.HasOne("OrderManagementSystem.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("Warehouse_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.ParcelOutbound", b =>
                {
                    b.HasOne("OrderManagementSystem.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("Warehouse_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.ParcelProductList", b =>
                {
                    b.HasOne("OrderManagementSystem.Models.ParcelOutbound", "ParcelOutbound")
                        .WithMany("ParcelProductLists")
                        .HasForeignKey("Order_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagementSystem.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("Product_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("ParcelOutbound");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.UserRole", b =>
                {
                    b.HasOne("OrderManagementSystem.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("Role_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagementSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.BillingAccount", b =>
                {
                    b.Navigation("Billings");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.InboundOrder", b =>
                {
                    b.Navigation("InboundProductLists");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.ParcelOutbound", b =>
                {
                    b.Navigation("ParcelProductLists");
                });

            modelBuilder.Entity("OrderManagementSystem.Models.User", b =>
                {
                    b.Navigation("BillingAccounts");

                    b.Navigation("Billings");
                });
#pragma warning restore 612, 618
        }
    }
}
